#
# Executes commands at logout.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Source local zlogout if any
#
if [[ -f "${ZDOTDIR:-$HOME}/.zsh/zlogout.local.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zsh/zlogout.local.zsh"
fi
